---   # Такая строка показывает нам что документ является форматом yml
- hosts: all # Определение на каком хосте или группе хоство будет применяться данный плейбук. Так же стоит отметить inventory файл в котором прописываются группы 
  become: yes # До того как мы установим NTP Нам нужны привелегии для модификации системы "Мы говорим ансибл Become root пользователем" те sudo
  tasks: # После данной строки все комманды будут запущены на заранее определенных машинах hosts:
    - name: Emsure NTP (for time synchronization ) is installed. # Эти команды эквиваленты yum intall ntp но в более продвинутый вариант
      yum: name=ntp state=present # если ntp не установлен в системе, ансибел применить команду. в ином случае пропустит как в bash скрипте.
    - name: Ensure NTP is running. # Эта последняя часть плейбука, 
      service: name=ntpd state=started enabled=yes # проверяет и гарантирует что ntpd сервис запустился и добавлен в список автозагрузок
#----------------------------------------------------------------------------------    Аналогия в виде bash script
# Start ntpd if it's not already running.
# if ps aux | grep -v grep | grep "[n]tpd" > /dev/null 
#  then
#    echo "ntpd is running." > /dev/null 
# else
#  systemctl start ntpd.service > /dev/null
#  echo "Started ntpd."
# fi 
# # Make sure ntpd is enabled on system startup.systemctl enable ntpd.service You
#  not human readebli version
#  ---
#   - hosts: all
#     become: yes
#     tasks:
#     - yum: name=ntp state=present 
#     - service: name=ntpd state=started enabled=yes